Backend:
  - MaxCherya
Frontend:
  - Senses-1
  - MaxCherya
DevOps:
  - MaxCherya
QA & Testing:
  - MaxCherya
Integrations:
  - MaxCherya
Data & Analytics:
  - MaxCherya
Product Management:
  - MaxCherya
Design & UX:
  - MaxCherya
  - Senses-1
Documentation:
  - MaxCherya
  - Senses-1
Security:
  - MaxCherya