blank_issues_enabled: false

contact_links:
  - name: 🔒 Security Issues
    url: https://github.com/Kybrium/experiment-40/security/policy
    about: Please report security vulnerabilities here (see SECURITY.md).
  - name: 📚 Project Docs
    url: https://github.com/Kybrium/experiment-40#-navigation
    about: Read the setup and usage documentation before opening an issue.