name: Django tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      SECRET_KEY: ci-secret-key
      DEBUG: "0"
      DATABASE_URL: sqlite:///./ci.sqlite3
      ALLOWED_HOSTS: "localhost,127.0.0.1"

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run migrations
        run: |
          python backend/manage.py migrate --noinput

      - name: Run tests
        run: |
          python backend/manage.py test --parallel --verbosity 2